local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20
  publish_frequency: 0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05
  transform_tolerance: 2.0
  cost_scaling_factor: 5
  inflation_radius: 0.6
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}