<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">
    <xacro:macro name="front_wheels_func" params="name flag">
        <link name="${name}_steering">
            <visual>
                <geometry>
                    <cylinder radius="0.01" length="0.1"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.01" length="0.1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="0.5" />
                <inertia ixx="1.35E-05" ixy="0" ixz="0" iyy="1.35E-05" iyz="0" izz="2.5E-05" />
            </inertial>
        </link>
        <joint name="${name}_steering2chasis" type="revolute">
            <parent link="chasis"/>
            <child link="${name}_steering"/>
            <axis xyz="0 0 1"/>
            <limit lower="-1.52" upper="1.52" velocity="1.0" effort="1000.0"/>
            <origin xyz="${chasis_l/2-wheel_r} ${flag*(chasis_w/2-wheel_l/2)} ${-(wheel_r+chasis_h/2)}" rpy="0 0 0"/>
        </joint>
        <transmission name="${name}_steering2chasis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_steering2chasis">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_steering2chasis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </actuator>
        </transmission>
        <link name="front_${name}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_l}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_l}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_r}" h="${wheel_l}"/>
        </link>
        <joint name="${name}2steering" type="continuous">
            <parent link="${name}_steering"/>
            <child link="front_${name}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </joint>
        <transmission name="${name}2steering_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}2steering">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}2steering_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>
    <xacro:front_wheels_func name="left" flag="1"/>
    <xacro:front_wheels_func name="right" flag="-1"/>
</robot>