<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">
    <link name="imu">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.01"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.01"/>
            </geometry>
        </collision>
        <xacro:box_inertial_matrix m="0.01" l="0.05" w="0.05" h="0.01"/>
    </link>
    <joint name="imu2chasis" type="fixed">
        <parent link="chasis"/>
        <child link="imu"/>
        <origin xyz="0.0 0.0 ${chasis_h/2+0.005}" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="imu">
        <material>Gazebo/Orange</material>
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>imu</bodyName>
                <updateRateHZ>100.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu</frameName>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
</gazebo>
</robot>