<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racercar">
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_r}" length="${lidar_l}"/>
            </geometry>
        </visual>
        <xacro:cylinder_inertial_matrix m="${lidar_m}" r="${lidar_r}" h="${lidar_l}"/>
    </link>
    <joint name="lidar2chasis" type="fixed">
        <parent link="chasis"/>
        <child link="lidar"/>
        <origin xyz="${chasis_l/2-wheel_r-imu_l/2-lidar_r} 0.0 ${chasis_h*2+lidar_l}" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="lidar">
        <sensor type="ray" name="rplidar">
            <pose>0 0 ${lidar_l} 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3</min_angle>
                        <max_angle>3</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>lidar</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>