<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">
    <xacro:macro name="rear_wheels_func" params="name flag">
        <link name="rear_${name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_l}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0"/>
            </visual>
            
            <collision>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_l}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_r}" h="${wheel_l}"/>
        </link>
        <joint name="rear_${name}2chasis" type="continuous">
            <parent link="chasis"/>
            <child link="rear_${name}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="${-(chasis_l/2-wheel_r)} ${flag*(chasis_w/2-wheel_l/2)} ${-(wheel_r+chasis_h/2)}"/>
        </joint>
        <transmission name="rear_${name}2chasis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="rear_${name}2chasis">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="rear_${name}2chasis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>
        <gazebo reference="rear_${name}_wheel">
            <mu1 value="10.0"/>
            <mu2 value="10.0"/>
            <kp value="1000000.0" />
            <kd value="10.0" />
        </gazebo>
    </xacro:macro>
    <xacro:rear_wheels_func name="left" flag="1"/>
    <xacro:rear_wheels_func name="right" flag="-1"/>
</robot>