tracer:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  platform2chasis_position_controller:
    type: position_controllers/JointPositionController
    joint: platform2chasis
    pid: {p: 100.0, i: 0.1, d: 1.0}
  
  left2chasis_position_controller:
    type: effort_controllers/JointEffortController
    joint: left2chasis
    pid: {p: 100.0, i: 0.1, d: 1.0}
  right2chasis_position_controller:
    type: effort_controllers/JointEffortController
    joint: right2chasis
    pid: {p: 100.0, i: 0.1, d: 1.0}
  
  # gazebo_ros_control:
  #   pid_gains:
  #     left2chasis: {p: 100.0, i: 0.1, d: 1.0}
  #     right2chasis: {p: 100.0, i: 0.1, d: 1.0}
      # platform2chasis: {p: 100.0, i: 0.1, d: 1.0}