<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </visual>
        <!-- <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision> -->
        <xacro:cylinder_inertial_matrix m="${lidar_mass}" r="${lidar_radius}" h="${lidar_length}"/>
        <transmission name="lidar2chasis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="lidar2chasis">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="lidar2chasis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
            </actuator>
        </transmission>
    </link>
    <!-- <joint name="lidar2chasis" type="prismatic">
        <parent link="chasis"/>
        <child link="lidar"/>
        <origin xyz="0.0 0.0 ${chasis_length/2+lidar_length/2}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1.0"/>
        <limit lower="0.0" upper="1.0" effort="0.1" velocity="0.1"/>
    </joint> -->
    <joint name="lidar2chasis" type="fixed">
        <parent link="chasis"/>
        <child link="lidar"/>
        <origin xyz="0.0 0.0 ${chasis_length/2+lidar_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="lidar">
        <sensor type="ray" name="rplidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3</min_angle>
                        <max_angle>3</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>lidar</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>