<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <xacro:macro name="sphere_func" params="sphere_name flag">
        <link name="${sphere_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
            </collision>
            <xacro:sphere_inertial_matrix m="${sphere_mass}" r="${sphere_radius}"/>
        </link>
        <joint name="${sphere_name}2chasis" type="continuous">
            <parent link="chasis"/>
            <child link="${sphere_name}_wheel"/>
            <origin xyz="${flag*0.3} 0.0 ${(sphere_radius+chasis_length/2)*-1}" rpy="0.0 0.0 0.0"/>
            <axis xyz="1 1 1" />
        </joint>
        <transmission name="${sphere_name}2chasis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${sphere_name}2chasis">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${sphere_name}2chasis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>
    <xacro:sphere_func sphere_name="front" flag = "1"/>
    <xacro:sphere_func sphere_name="behind" flag = "-1"/>
</robot>